[project]
name = "mtlshed"
description = "dumber mtls cert mgmt tool"
version = "0.0.1"

[project.scripts]
mtlshed = "mtlshed.certs:main"

[build-system]
build-backend = 'setuptools.build_meta'
requires = [
    'setuptools', 'wheel'
]

